tasks:
  - type: docker-build
    image: website
    auto:
      - source: push
        has_tag: true
        tag_source: tag
      - source: push
        has_tag: true
        tag_source: latest
    context: .
    file: Dockerfile
    registries:
      - gitlab
