services:
  website:
    image: registry.gitlab.com/haondt/cicd/registry/website:latest
    networks:
      - nginx
    env_file:
      - ./website/website.env
    volumes:
      - ./website/assets:/assets
    environment:
      VIRTUAL_HOST: noahburghardt.ca
      LETSENCRYPT_HOST: noahburghardt.ca
      VIRTUAL_PORT: 8080
