version: '3'

services:
        frontend:
                build:
                        context: ./frontend
                working_dir: /code
                volumes:
                        - ./frontend/frontend:/code/
                          # data volume to persist node modules from build stage
                        - /code/node_modules 
                ports:
                        - "3000:3000"
                stdin_open: true # docker run -i
                tty: true # docker run -t
        backend:
                build:
                        context: ./backend
                working_dir: /code
                command: python3 app.py
                volumes:
                        - ./backend/flask:/code
                        - /projects
                ports:
                        - "8000:8000"
                networks:
                        - backend_network
                depends_on:
                        - db
        db:
                image: mysql:5.7
                environment:
                        MYSQL_DATABASE: 'my-app-db'
                        MYSQL_ROOT_PASSWORD: 'password'
                networks:
                        - backend_network

networks:
        backend_network:
                driver: bridge



