version: '3'

services:
        backend:
                build:
                        context: ./backend
                working_dir: /code
                command: python3 app.py
                volumes:
                        - ./backend/flask:/code
                        - /projects
                networks:
                        - backend_network
        nginx:
                build:
                        context: .
                        dockerfile: ./nginx/Dockerfile
                ports:
                        - "80:80"
                        - "443:443"
                depends_on:
                        - backend
                volumes:
                        - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro
                        - ./certbot/conf:/etc/letsencrypt
                        - ./certbot/www:/var/www/certbot
                networks:
                        - backend_network
                command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        certbot:
                image: certbot/certbot
                volumes:
                        - ./certbot/conf:/etc/letsencrypt
                        - ./certbot/www:/var/www/certbot
                entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
        backend_network:
                driver: bridge



