name: Deploy
on:
  push:
    branches:
      - htmx
#  release:
#    types: [published]
#    tags: ['v*.*.*']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to remote machine and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/website/deploy
            git pull